print("        *\t\t\t*")
print("       * *\t\t       * *")
print("      *   *\t\t      *   *")
print("     *     *\t\t     *     *")
print("    *       *\t\t    *       *")
print("   *         *\t\t   *         *")
print("  *           *\t\t  *           *")
print(" *             *\t *             *")
print("******     ******\t******     ******")
print("     *     *\t\t     *     *")
print("     *     *\t\t     *     *")
print("     *     *\t\t     *     *")
print("     *     *\t\t     *     *")
print("     *     *\t\t     *     *")
print("     *     *\t\t     *     *")
print("     *******\t\t     *******")