print("Hola, porfavor ingrese su nombre:")
nombre = input()
print("Porfavor, ingrese su apellido:")
apellido = input()
print("Finalmente, ingrese su edad porfavor:")
edad = int(input())
print(f"Muchas gracias {nombre} {apellido}. Lamentablemente necesitamos participantes con, minimamente, {edad + 3} años de edad, y usted solo tiene {edad}. Sin embargo, esperamos su participación en el próximo Pequeño Hermano\nAtte. Telefe")